### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "test@gmail.com",
    "password": "123456"
}

### Signin user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "test@gmail.com",
    "password": "123456"
}


### Create a new user 2
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "test2@gmail.com",
    "password": "123456"
}

### Create a new user 3
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "test3@gmail.com",
    "password": "123456"
}

### Create a new user 4
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "test4@gmail.com",
    "password": "123456"
}





### Signin user 2
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "test2@gmail.com",
    "password": "123456"
}


### Signin user 3
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "test3@gmail.com",
    "password": "123456"
}

### Signin user 4
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "test4@gmail.com",
    "password": "123456"
}





### Get user with id 1
GET http://localhost:3000/auth/1

### Get users with id 2
GET http://localhost:3000/auth/2

### Find all users with given email
GET http://localhost:3000/auth?email=test@gmail.com

### Delete user with id 1
DELETE http://localhost:3000/auth/1

### Update user with id 2
PATCH http://localhost:3000/auth/2
content-type: application/json

{
    "email": "updated@gmail.com"
}

### Get the current user
GET http://localhost:3000/auth/whoami

### Signout user
POST http://localhost:3000/auth/signout