### Create a new report
POST http://localhost:3000/reports
content-type: application/json

{
  "make": "Hyundai",
  "model": "Sonata",
  "year": 2020,
  "mileage": 50000,
  "lng": 127.0,
  "lat": 37.5,
  "price": 15000
}

### Approve a report
PATCH http://localhost:3000/reports/1
content-type: application/json

{
  "approved": true
}

### GEt an estimate for an existing vehicle
GET http://localhost:3000/reports/estimate?make=Hyundai&model=Sonata&lng=0&lat=0&mileage=20000&year=1980
